import 'dart:async';
import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:email_validator/email_validator.dart';
import 'package:file_picker/file_picker.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:image_picker/image_picker.dart';
import 'package:portolink_user/models/models.dart';
import 'package:portolink_user/services/services.dart';
import 'package:portolink_user/ui/widgets/widgets.dart';

part 'splash.dart';
part 'login.dart';
part 'register.dart';
part 'listtemplate.dart';
part 'dashboard.dart';
part 'myaccount.dart';
part 'mainmenu.dart';
part 'pendingrequest.dart';
part 'ordertemplate.dart';
part 'requesttemplate.dart';
part 'updateaccount.dart';
part'ourcontact.dart';